---

- name: Clean DNF cache
  become: true
  ansible.builtin.dnf:
    autoremove: true
    update_cache: true

- name: Import Foreman GPG key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "https://yum.theforeman.org/releases/{{ foreman_repositories_version }}/RPM-GPG-KEY-foreman"

- name: Install Foreman release package
  become: true
  ansible.builtin.dnf:
    name: "https://yum.theforeman.org/releases/{{ foreman_repositories_version }}/el{{ ansible_distribution_major_version }}/x86_64/foreman-release.rpm"
    state: present

- name: Import Puppet GPG key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://yum.puppet.com/RPM-GPG-KEY-puppet

- name: Install Puppet 8 release package
  become: true
  ansible.builtin.dnf:
    name: "https://yum.puppet.com/puppet{{ foreman_puppet_version }}-release-el-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

...
