---

name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore
      - ./meta/main.yml
      - LICENSE

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  almalinux9:
    name: AlmaLinux 9
    uses: philnewm/ansible-role-repo-control/.github/workflows/molecule-ci-podman.yml@main
    with:
      scenario_name: almalinux9

  centosstream9:
    name: Centos Stream 9
    uses: philnewm/ansible-role-repo-control/.github/workflows/molecule-ci-podman.yml@main
    with:
      scenario_name: centosstream9

  rocky9:
    name: Rocky 9
    uses: philnewm/ansible-role-repo-control/.github/workflows/molecule-ci-podman.yml@main
    with:
      scenario_name: rocky9

  # debian12:
  #   name: Debian 12
  #   uses: philnewm/ansible-role-repo-control/.github/workflows/molecule-ci-podman.yml@main
  #   with:
  #     scenario_name: debian12

  # ubuntu2204:
  #   name: Ubuntu 2204
  #   uses: philnewm/ansible-role-repo-control/.github/workflows/molecule-ci-podman.yml@main
  #   with:
  #     scenario_name: ubuntu2204

...
