---

name: Debian12-CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore
      - ./meta/main.yml
      - LICENSE

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore

permissions:
  contents: read

jobs:
  debian12-ci:
    uses: philnewm/ansible-role-repo-control/.github/workflows/molecule-ci-libvirt.yml@main
    with:
      scenario_name: debian12

...
